version: '3.1'

services:

  db:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: open
      POSTGRES_DB: team-manage-app

    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
